name: Run tests
on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build tools and Rust
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential libpq-dev
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup install stable
          rustup default stable

      - name: Check Rust version
        run: rustc --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --prefer-binary -r requirements.txt

      - name: Run tests
        run: python -m pytest ./tests
